// This file will be auto-generated by:
// npx supabase gen types typescript --project-id <project-id> > src/types/database.ts
//
// Placeholder type until Supabase schema is set up
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
